version: '3'
services:

  bergen-db:
    image: 'postgres:14.1-alpine'
    environment:
    - DB_NAME=msg
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
    - /tmp/bergen/var/lib/postgresql/data:/var/lib/postgresql/data
#    - /tmp/bergen/tmp/pgdb:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432
    restart: always
#    networks:
#      default:
#        ipv4_address: 192.168.9.4

  bergen-msg:
    build:
      context: ./docker
      args:
        - ARTEMIS_USER=$ARTEMIS_USER
        - ARTEMIS_PASSWORD=$ARTEMIS_PASSWORD
    container_name: bergen-msg
    volumes:
      # Expose some outstanding folders
      - /tmp/bergen/var/lib/broker/data:/var/lib/broker-instance/data
      - ./docker/broker.xml:/var/lib/broker-instance/etc/broker.xml
    ports:
      # Web Server
      - 8161:8161
      # JMX Exporter
      - 9404:9404
      # Port for CORE,MQTT,AMQP,HORNETQ,STOMP,OPENWIRE
      - 61616:61616
      # Port for HORNETQ,STOMP
      - 5445:5445
      # Port for AMQP
      - 5672:5672
      # Port for MQTT
      - 1883:1883
      #Port for STOMP
      - 61613:61613
#    networks:
#      default:
#        ipv4_address: 192.168.9.2
